export const Message = {
  dataApproved: "Data approved",
  dataRejected: "Data rejected",
  dataPosponed: "Data postponed",
  dataRetrieved: "Data retrieved",
  dataExist: "Data already exist.",
  dataCreated: "Data successfully created!",
  dataFound: "Data found",
  dataNotFoundWithId: "Data not found with id:",
  dataNotFoundWithSession: "Data not found with session:",
  dataUpdated: "Data update success",
  dataDeleted: "Data has been deleted",
  noDataFound: "Belum ada data",
  failedUpdateData: "Failed to update data with id:",
  noVendorFound: "Vendor not found with id:",
  invalidNumeric: "Please input a valid numeric value!",
  mailSent: "Mail successfully sent!",
  mailFailed: "Mail sent failed!",
  noParentFound: "No parent found",
  pleaseProvideDetail: "Please provide complete details",
  sessionExpired: "Session expired",
  cannotDeleteVendor: "Vendor tidak dapat di delete",
  noNotif: "Tidak ada Notifikasi",
};
